# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdoraUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdoraUi(object):
    def setupUi(self, AdoraUi):
        AdoraUi.setObjectName("AdoraUi")
        self.centralwidget = QtWidgets.QWidget(AdoraUi)
        self.centralwidget.setObjectName("centralwidget")
        self.Bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_1.setGeometry(QtCore.QRect(-190, -130, 1911, 1071))
        self.Bg_1.setText("")
        self.Bg_1.setPixmap(QtGui.QPixmap("Gui_Materials/B.G/Black_Template.jpg"))
        self.Bg_1.setScaledContents(True)
        self.Bg_1.setObjectName("Bg_1")
        self.Gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_1.setGeometry(QtCore.QRect(710, 0, 651, 401))
        self.Gif_1.setText("")
        self.Gif_1.setPixmap(QtGui.QPixmap("C:/Users/admin/Downloads/img_0119.gif"))
        self.Gif_1.setScaledContents(True)
        self.Gif_1.setObjectName("Gif_1")
        self.Gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_2.setGeometry(QtCore.QRect(4, 9, 701, 171))
        self.Gif_2.setText("")
        self.Gif_2.setPixmap(QtGui.QPixmap("Gui_Materials/ExtraGui/initial.gif"))
        self.Gif_2.setScaledContents(True)
        self.Gif_2.setObjectName("Gif_2")
        self.Gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_3.setGeometry(QtCore.QRect(600, 405, 761, 311))
        self.Gif_3.setText("")
        self.Gif_3.setPixmap(QtGui.QPixmap("Gui_Materials/ExtraGui/B.G_Template_1.gif"))
        self.Gif_3.setScaledContents(True)
        self.Gif_3.setObjectName("Gif_3")
        self.Gif_4 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_4.setGeometry(QtCore.QRect(344, 99, 361, 331))
        self.Gif_4.setText("")
        self.Gif_4.setPixmap(QtGui.QPixmap("Gui_Materials/ExtraGui/Mr3W.gif"))
        self.Gif_4.setScaledContents(True)
        self.Gif_4.setObjectName("Gif_4")
        self.Bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_2.setGeometry(QtCore.QRect(-16, 160, 291, 91))
        self.Bg_2.setText("")
        self.Bg_2.setPixmap(QtGui.QPixmap("C:/Users/admin/Pictures/Text_input.jpg"))
        self.Bg_2.setScaledContents(True)
        self.Bg_2.setObjectName("Bg_2")
        self.Bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_3.setGeometry(QtCore.QRect(-20, 250, 291, 91))
        self.Bg_3.setText("")
        self.Bg_3.setPixmap(QtGui.QPixmap("C:/Users/admin/Pictures/Text_input.jpg"))
        self.Bg_3.setScaledContents(True)
        self.Bg_3.setObjectName("Bg_3")
        self.Bg_4 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_4.setGeometry(QtCore.QRect(-20, 340, 291, 91))
        self.Bg_4.setText("")
        self.Bg_4.setPixmap(QtGui.QPixmap("C:/Users/admin/Pictures/Text_input.jpg"))
        self.Bg_4.setScaledContents(True)
        self.Bg_4.setObjectName("Bg_4")
        self.pushButton_YouTube = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_YouTube.setGeometry(QtCore.QRect(60, 190, 131, 28))
        self.pushButton_YouTube.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);\n"
"font: 12pt \"Courier New\";\n"
"font: 18pt \"Courier\";\n"
"color: rgb(0, 255, 0);\n"
"")
        self.pushButton_YouTube.setObjectName("pushButton_YouTube")
        self.pushButton_Chrome = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Chrome.setGeometry(QtCore.QRect(50, 280, 131, 28))
        self.pushButton_Chrome.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);\n"
"font: 12pt \"Courier New\";\n"
"font: 18pt \"Courier\";\n"
"color: rgb(0, 255, 0);\n"
"")
        self.pushButton_Chrome.setObjectName("pushButton_Chrome")
        self.PushButton_Whatsapp = QtWidgets.QPushButton(self.centralwidget)
        self.PushButton_Whatsapp.setGeometry(QtCore.QRect(60, 370, 131, 28))
        self.PushButton_Whatsapp.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);\n"
"font: 12pt \"Courier New\";\n"
"font: 18pt \"Courier\";\n"
"color: rgb(0, 255, 0);\n"
"")
        self.PushButton_Whatsapp.setObjectName("PushButton_Whatsapp")
        self.Bg_5 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_5.setGeometry(QtCore.QRect(-10, 550, 291, 91))
        self.Bg_5.setText("")
        self.Bg_5.setPixmap(QtGui.QPixmap("C:/Users/admin/Pictures/Text_input.jpg"))
        self.Bg_5.setScaledContents(True)
        self.Bg_5.setObjectName("Bg_5")
        self.Bg_6 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_6.setGeometry(QtCore.QRect(260, 550, 291, 91))
        self.Bg_6.setText("")
        self.Bg_6.setPixmap(QtGui.QPixmap("C:/Users/admin/Pictures/Text_input.jpg"))
        self.Bg_6.setScaledContents(True)
        self.Bg_6.setObjectName("Bg_6")
        self.PushButton_Start = QtWidgets.QPushButton(self.centralwidget)
        self.PushButton_Start.setGeometry(QtCore.QRect(60, 580, 131, 28))
        self.PushButton_Start.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);\n"
"font: 12pt \"Courier New\";\n"
"font: 22pt \"Courier\";\n"
"color: rgb(0, 255, 0);\n"
"")
        self.PushButton_Start.setObjectName("PushButton_Start")
        self.PushButton_Exit = QtWidgets.QPushButton(self.centralwidget)
        self.PushButton_Exit.setGeometry(QtCore.QRect(340, 580, 131, 28))
        self.PushButton_Exit.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);\n"
"font: 22pt \"Courier New\";\n"
"font: 18pt \"Courier\";\n"
"color: rgb(0, 255, 0);\n"
"")
        self.PushButton_Exit.setObjectName("PushButton_Exit")
        AdoraUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(AdoraUi)
        QtCore.QMetaObject.connectSlotsByName(AdoraUi)

    def retranslateUi(self, AdoraUi):
        _translate = QtCore.QCoreApplication.translate
        AdoraUi.setWindowTitle(_translate("AdoraUi", "MainWindow"))
        self.pushButton_YouTube.setText(_translate("AdoraUi", "YouTube"))
        self.pushButton_Chrome.setText(_translate("AdoraUi", "Chrome"))
        self.PushButton_Whatsapp.setText(_translate("AdoraUi", "WhatsApp"))
        self.PushButton_Start.setText(_translate("AdoraUi", "START"))
        self.PushButton_Exit.setText(_translate("AdoraUi", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdoraUi = QtWidgets.QMainWindow()
    ui = Ui_AdoraUi()
    ui.setupUi(AdoraUi)
    AdoraUi.show()
    sys.exit(app.exec_())
